create table Appointment (	id bigint generated by default as identity (start with 1), 
						  	dateTime timestamp, 
						  	notes varchar(255), 
							owner varchar(255), 
							ownerPhone varchar(255), 
							pet varchar(255), 
							primary key (id));
grant all on 
	class "com.springsource.insight.plugin.jdbc.StoredProcedureExample" 
	to public;
create alias testSp for 
	"com.springsource.insight.plugin.jdbc.StoredProcedureExample.testSp";